version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map backend port to host
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map frontend port to host
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:
